# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pots.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1, validators=[pots.models.at_least_one])),
                ('loss_count', models.IntegerField(blank=True, validators=[pots.models.at_least_one])),
                ('loss_public', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[(b'deployed', b'Deployed'), (b'lost', b'Lost'), (b'collected', b'Collected')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'pot', max_length=50)),
                ('type', models.CharField(default=b'Lobster', max_length=50)),
                ('top', models.CharField(blank=True, max_length=50)),
                ('middle', models.CharField(blank=True, max_length=50)),
                ('bottom', models.CharField(blank=True, max_length=50)),
                ('base', models.CharField(blank=True, max_length=50)),
                ('contrast', models.CharField(blank=True, max_length=50)),
                ('placement', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='pot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pots.Pot'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='pot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='pots.Pot'),
        ),
    ]
