# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import pots.models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'Ishmael', max_length=50)),
                ('password', models.CharField(default=b'********', max_length=50)),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deployment',
            name='loss_count',
            field=models.IntegerField(blank=True, null=True, validators=[pots.models.at_least_one]),
        ),
    ]
