# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0003_auto_20160423_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='name',
            field=models.CharField(default='pot', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='pot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pots.Pot'),
        ),
    ]
