# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pots.models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0007_auto_20160423_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1, validators=[pots.models.at_least_one])),
                ('loss_count', models.IntegerField(blank=True, validators=[pots.models.at_least_one])),
                ('loss_public', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[(b'deployed', b'Deployed'), (b'lost', b'Lost'), (b'collected', b'Collected')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pot',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='count',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pot',
            name='state',
        ),
        migrations.AddField(
            model_name='pot',
            name='base',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pot',
            name='bottom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pot',
            name='contrast',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pot',
            name='middle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pot',
            name='placement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pot',
            name='top',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pot',
            name='type',
            field=models.CharField(default=b'Lobster', max_length=50),
        ),
        migrations.AlterField(
            model_name='pot',
            name='name',
            field=models.CharField(default=b'pot', max_length=50),
        ),
        migrations.AddField(
            model_name='deployment',
            name='pot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='pots.Pot'),
        ),
    ]
